apiVersion: v1
kind: Service
metadata:
  name: question-service
  namespace: interview-coach
  labels:
    app: question-service
spec:
  selector:
    app: question-service
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
  type: ClusterIP
