apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: interview-coach
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: interview-coach
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-service
  namespace: interview-coach
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: interview-service
  namespace: interview-coach
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-service
  namespace: interview-coach
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: interview-coach
spec:
  replicas: 2
