apiVersion: v1
kind: Secret
metadata:
  name: interview-coach-secret
  namespace: interview-coach
type: Opaque
stringData:
  DATABASE_PASSWORD: "postgres"
  JWT_SECRET: "change-this-in-production-must-be-at-least-256-bits"
  CLAUDE_API_KEY: ""
  OPENAI_API_KEY: ""
